site_name: fastapi-users-firebase
repo_url: https://github.com/francipvb/fastapi-users-firebase
site_url: https://francipvb.github.io/fastapi-users-firebase
site_description: This is a plugin for the FastAPI Users library to integrate Firebase Authentication to the app.
site_author: Francisco Del Roio
edit_uri: edit/main/docs/
repo_name: francipvb/fastapi-users-firebase
copyright: Maintained by <a href="https://francipvb.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/francipvb/fastapi-users-firebase
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/fastapi-users-firebase

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
